{ lib, inventory }:
with lib;
let
  inherit (inventory)
    hosts
    roles
    networks
    users
    activeRoles
    teams
    clusters
    ;

  admins = filterAttrs (_: u: u.cohort == "admin") users;
  adminAge = unique (concatLists (mapAttrsToList (_: u: u.keys.age) admins));

  machineAge = id: inventory.machineAge.${id} or [ ];
  hostsOfRole = r: filter (h: elem r h.roles) (attrValues hosts);

  rackedHosts = filterAttrs (_: h: h.location.kind == "rack") hosts;

  primaryMac =
    h:
    let
      datas = filter (n: n.role == "data") h.nics;
    in
    if datas == [ ] then null else (head datas).mac;

  headscaleId = uid: users.${uid}.headscale_user or uid;

in
{
  sopsYaml =
    {
      pkgs,
      bootstrapAge ? [ ],
    }:
    let
      perHost = mapAttrsToList (_: h: {
        path_regex = "^secrets/hosts/${h.id}\\.yml$";
        age = adminAge ++ machineAge h.id;
      }) hosts;

      perRole = mapAttrsToList (r: _: {
        path_regex = "^secrets/roles/${r}\\.yml$";
        age = adminAge ++ concatLists (map (h: machineAge h.id) (hostsOfRole r));
      }) roles;

      perCluster = mapAttrsToList (cid: _: {
        path_regex = "^secrets/clusters/${cid}\\.yml$";
        age = adminAge ++ concatLists (map machineAge (inventory.hostsByCluster.${cid} or [ ]));
      }) clusters;

      cluster = {
        path_regex = "^secrets/cluster\\.yml$";
        age = adminAge;
      };

      system = {
        path_regex = "^secrets/system\\.yaml$";
        age = adminAge ++ bootstrapAge ++ concatLists (mapAttrsToList (id: _: machineAge id) hosts);
      };

      yaml = builtins.toJSON {
        creation_rules = [
          cluster
          system
        ]
        ++ perCluster
        ++ perHost
        ++ perRole;
      };
    in
    pkgs.runCommand "sops-yaml"
      {
        nativeBuildInputs = [ pkgs.remarshal ];
        yamlInput = yaml;
        passAsFile = [ "yamlInput" ];
      }
      ''
        remarshal -if json -of yaml -i "$yamlInputPath" -o $out
        echo "# AUTO-GENERATED by cluster-config codegen. Do not edit." | cat - $out > $out.tmp
        mv $out.tmp $out
      '';

  matchbox =
    { pkgs }:
    let
      profile = r: {
        id = "role-${r}";
        name = "Role: ${r}";
        boot = {
          kernel = "/assets/cluster-installer/bzImage";
          initrd = [ "/assets/cluster-installer/initrd" ];
          args = [
            "init=/init"
            "console=ttyS0,115200n8"
            "console=tty0"
            "cluster.role=${r}"
            "cluster.matchbox=https://matchbox.cluster.local"
          ];
        };
      };

      group = h: {
        inherit (h) id;
        name = h.id;
        profile = "role-${head h.roles}";
        selector.mac = primaryMac h;
        metadata = {
          inherit (h) hostname;
          rack = h.location.rack;
          inherit (h) roles;
        };
      };

      profileFiles = mapAttrsToList (r: _: {
        path = "profiles/${r}.json";
        data = builtins.toJSON (profile r);
      }) (filterAttrs (r: _: elem r activeRoles) roles);

      groupFiles = mapAttrsToList (_: h: {
        path = "groups/${h.id}.json";
        data = builtins.toJSON (group h);
      }) (filterAttrs (_: h: primaryMac h != null) rackedHosts);

      writeAll = concatStringsSep "\n" (
        map (f: ''
                mkdir -p "$(dirname "$out/${f.path}")"
                cat > "$out/${f.path}" <<'EOF'
          ${f.data}
          EOF
        '') (profileFiles ++ groupFiles)
      );
    in
    pkgs.runCommand "matchbox" { } ''
      mkdir -p $out
          ${writeAll}'';

  kea =
    { pkgs }:
    let
      v4nets = filterAttrs (_: n: n.prefix_v4 != null) networks;
      idx = listToAttrs (
        imap1 (i: n: {
          name = n;
          value = i;
        }) (attrNames v4nets)
      );
      subnetId = id: n: if n.vlan_id != null then n.vlan_id + 1 else 1000 + idx.${id};

      subnet4 = mapAttrsToList (id: n: {
        subnet = n.prefix_v4;
        id = subnetId id n;
        reservations = [ ];
        option-data = optionals (n.gateway_v4 != null) [
          {
            name = "routers";
            data = n.gateway_v4;
          }
        ];
        user-context = {
          cluster_network_id = id;
          inherit (n) purpose;
          vrf = n.vrf or "";
        };
      }) v4nets;

      config = {
        Dhcp4 = {
          interfaces-config.interfaces = [ "*" ];
          lease-database = {
            type = "memfile";
            persist = true;
            name = "/var/lib/kea/kea-leases4.csv";
          };
          valid-lifetime = 3600;
          inherit subnet4;
        };
      };
    in
    pkgs.runCommand "kea" { } ''
      mkdir -p $out
          cat > $out/kea-dhcp4.json <<'EOF'
      ${builtins.toJSON config}
      EOF'';

  headscaleAcl =
    { pkgs }:
    let
      activeClusters = filterAttrs (_: c: c.state != "retired") clusters;
      activeTeams = filterAttrs (
        _: t: any (c: any (g: g.team == t.id) c.access.teams) (attrValues activeClusters)
      ) teams;

      stripTag = s: if hasPrefix "tag:" s then substring 4 (stringLength s) s else s;

      baseOf =
        cid:
        let
          c = clusters.${cid};
        in
        if c.network.tailscale_tag != null then stripTag c.network.tailscale_tag else "cluster-${cid}";

      subTagsOf =
        cid:
        let
          base = baseOf cid;
          nonEmpty = bucket: bucket != [ ];
        in
        (optional (nonEmpty (inventory.loginNodesOfCluster.${cid} or [ ])) "tag:${base}-login")
        ++ (optional (nonEmpty (inventory.computeNodesOfCluster.${cid} or [ ])) "tag:${base}-compute")
        ++ (optional (nonEmpty (inventory.storageNodesOfCluster.${cid} or [ ])) "tag:${base}-storage")
        ++ (optional (nonEmpty (
          inventory.controllerNodesOfCluster.${cid} or [ ]
        )) "tag:${base}-controller");

      broadTagOf = cid: "tag:${baseOf cid}";

      loginTagOf =
        cid:
        let
          base = baseOf cid;
        in
        if (inventory.loginNodesOfCluster.${cid} or [ ]) != [ ] then "tag:${base}-login" else "tag:${base}";

      computeTagOf =
        cid:
        let
          base = baseOf cid;
        in
        if (inventory.computeNodesOfCluster.${cid} or [ ]) != [ ] then "tag:${base}-compute" else null;
      storageTagOf =
        cid:
        let
          base = baseOf cid;
        in
        if (inventory.storageNodesOfCluster.${cid} or [ ]) != [ ] then "tag:${base}-storage" else null;

      groups =
        mapAttrs' (tid: t: {
          name = "group:${tid}";
          value = map (m: headscaleId m.user) t.members;
        }) activeTeams
        // {
          "group:admin" = map headscaleId (attrNames admins);
        };

      tagOwners =
        listToAttrs (
          concatMap (
            cid:
            let
              c = clusters.${cid};
              owners = [ "group:admin" ] ++ map (g: "group:${g.team}") c.access.teams;
              tags = [ (broadTagOf cid) ] ++ subTagsOf cid;
            in
            map (t: {
              name = t;
              value = owners;
            }) tags
          ) (attrNames activeClusters)
        )
        // {
          "tag:bootstrap" = [ "group:admin" ];
          "tag:drive-share" = [ "group:admin" ];
          "tag:drive-access" = [ "group:admin" ];
        };

      adminRule = {
        action = "accept";
        src = [ "group:admin" ];
        dst = (map (cid: "${broadTagOf cid}:*") (attrNames activeClusters)) ++ [ "tag:bootstrap:*" ];
      };

      driveRule = {
        action = "accept";
        src = [ "tag:drive-access" ];
        dst = [ "tag:drive-share:*" ];
      };

      computeMeshRules = concatMap (
        cid:
        let
          ct = computeTagOf cid;
          c = clusters.${cid};
        in
        if ct != null && c.network.intra_cluster == "mesh" then
          [
            {
              action = "accept";
              src = [ ct ];
              dst = [ "${ct}:*" ];
            }
          ]
        else
          [ ]
      ) (attrNames activeClusters);

      loginToComputeRules = concatMap (
        cid:
        let
          base = baseOf cid;
          haveLogin = (inventory.loginNodesOfCluster.${cid} or [ ]) != [ ];
          ct = computeTagOf cid;
        in
        if haveLogin && ct != null then
          [
            {
              action = "accept";
              src = [ "tag:${base}-login" ];
              dst = [ "${ct}:22" ];
            }
          ]
        else
          [ ]
      ) (attrNames activeClusters);

      computeToStorageRules =
        let
          intra = concatMap (
            cid:
            let
              c = clusters.${cid};
              ct = computeTagOf cid;
              st = storageTagOf cid;
              ports = c.network.storage.ports_tcp;
            in
            if ct != null && st != null && ports != [ ] then
              map (p: {
                action = "accept";
                src = [ ct ];
                dst = [ "${st}:${toString p}" ];
              }) ports
            else
              [ ]
          ) (attrNames activeClusters);
          inter = concatMap (
            cid:
            let
              c = clusters.${cid};
              ct = computeTagOf cid;
            in
            if ct == null then
              [ ]
            else
              concatMap (
                otherCid:
                if !(clusters ? ${otherCid}) then
                  [ ]
                else
                  let
                    other = clusters.${otherCid};
                    st = storageTagOf otherCid;
                    ports = other.network.storage.ports_tcp;
                  in
                  if st != null && ports != [ ] then
                    map (p: {
                      action = "accept";
                      src = [ ct ];
                      dst = [ "${st}:${toString p}" ];
                    }) ports
                  else
                    [ ]
              ) c.network.egress.clusters
          ) (attrNames activeClusters);
        in
        intra ++ inter;

      teamGrantRules = concatMap (
        cid:
        let
          c = clusters.${cid};
        in
        map (g: {
          action = "accept";
          src = [ "group:${g.team}" ];
          dst = [ "${loginTagOf cid}:*" ];
        }) c.access.teams
      ) (attrNames activeClusters);

      userGrantRules = concatMap (
        cid:
        let
          c = clusters.${cid};
        in
        map (g: {
          action = "accept";
          src = [ (headscaleId g.user) ];
          dst = [ "${loginTagOf cid}:*" ];
        }) c.access.users
      ) (attrNames activeClusters);

      egressClusterRules = concatMap (
        cid:
        let
          c = clusters.${cid};
        in
        concatMap (
          otherCid:
          if !(clusters ? ${otherCid}) then
            [ ]
          else
            map (g: {
              action = "accept";
              src = [ "group:${g.team}" ];
              dst = [ "${loginTagOf otherCid}:*" ];
            }) c.access.teams
        ) c.network.egress.clusters
      ) (attrNames activeClusters);

      teamSubmitRules = concatMap (
        cid:
        let
          c = clusters.${cid};
        in
        concatMap (
          g:
          map (otherCid: {
            action = "accept";
            src = [ "group:${g.team}" ];
            dst = [ "${loginTagOf otherCid}:*" ];
          }) g.can_submit_to
        ) c.access.teams
      ) (attrNames activeClusters);

      userSubmitRules = concatMap (
        cid:
        let
          c = clusters.${cid};
        in
        concatMap (
          g:
          map (otherCid: {
            action = "accept";
            src = [ (headscaleId g.user) ];
            dst = [ "${loginTagOf otherCid}:*" ];
          }) g.can_submit_to
        ) c.access.users
      ) (attrNames activeClusters);

      acls = [
        adminRule
        driveRule
      ]
      ++ computeMeshRules
      ++ loginToComputeRules
      ++ computeToStorageRules
      ++ teamGrantRules
      ++ userGrantRules
      ++ egressClusterRules
      ++ teamSubmitRules
      ++ userSubmitRules;

      nodeAttrs = [
        {
          target = [ "tag:drive-share" ];
          attr = [ "drive:share" ];
        }
        {
          target = [ "tag:drive-access" ];
          attr = [ "drive:access" ];
        }
      ];

      grants = [
        {
          src = [ "tag:drive-access" ];
          dst = [ "tag:drive-share" ];
          app = {
            "tailscale.com/cap/drive" = [
              {
                shares = [ "*" ];
                access = "rw";
              }
            ];
          };
        }
      ];

      policy = {
        inherit
          groups
          tagOwners
          acls
          nodeAttrs
          grants
          ;
      };

      banner = ''
        // AUTO-GENERATED by cluster-config codegen. Do not edit.
        //
        // Derived from inventory/clusters/, inventory/teams/, inventory/roles/
        // (node_role), and inventory/access-tiers/. Regenerate with
        // `nix build .#headscale-acl`.
        //
        // Layers of enforcement (this is the outermost):
        //   1. headscale ACL (this file)        - reachability on the overlay
        //   2. nftables on each host (TODO)     - L3/L4 packet filter
        //   3. slurm AssocMgr / partition QoS   - job submission
        //   4. pam_slurm_adopt + sshd Match     - SSH only if user has alloc
      '';
    in
    pkgs.runCommand "headscale-acl" { } ''
          mkdir -p $out
          cat > $out/policy.hujson <<'EOF'
      ${banner}
      ${builtins.toJSON policy}
      EOF
    '';

  hostNetFacts = mapAttrs (_: h: {
    hostId = h.id;
    inherit (h) hostname;
    inherit (h) location;
    nics = map (n: n // { network = networks.${n.network} or { }; }) h.nics;
    inherit (h) bgp;
    cluster = inventory.hostToCluster.${h.id} or null;
    ownerTeam = inventory.hostOwnerTeam.${h.id} or null;
  }) hosts;
}
