{
  lib,
  inventory,
  headscalePolicy ? import ./headscale-policy.nix { inherit lib; },
}:
with lib;
let
  inherit (inventory)
    hosts
    deploymentRoles
    networks
    users
    activeDeploymentRoles
    teams
    clusters
    ;

  fleetAdmins = filterAttrs (_: u: elem "fleet" u.admin_scopes && !(u.archived or false)) users;
  tailnetAdmins = filterAttrs (_: u: elem "tailnet" u.admin_scopes && !(u.archived or false)) users;
  fleetAdminAge = unique (concatLists (mapAttrsToList (_: u: u.keys.age) fleetAdmins));

  machineAge = id: inventory.machineAge.${id} or [ ];
  hostsOfDeploymentRole = r: filter (h: elem r h.deployment_roles) (attrValues hosts);
  isActiveUser = uid: users ? ${uid} && !(users.${uid}.archived or false);

  rackedHosts = filterAttrs (_: h: h.location.kind == "rack") hosts;

  primaryMac =
    h:
    let
      datas = filter (n: n.role == "data") h.nics;
    in
    if datas == [ ] then null else (head datas).mac;

  headscaleId =
    uid:
    let
      configured = users.${uid}.headscale_user or null;
      username = if configured == null then uid else configured;
    in
    headscalePolicy.userPrincipal username;

in
{
  sopsYaml =
    {
      pkgs,
      bootstrapAge ? [ ],
    }:
    let
      perHost = mapAttrsToList (_: h: {
        path_regex = "^secrets/hosts/${h.id}\\.yml$";
        age = fleetAdminAge ++ machineAge h.id;
      }) hosts;

      perDeploymentRole = mapAttrsToList (r: _: {
        path_regex = "^secrets/deployment-roles/${r}\\.yml$";
        age = fleetAdminAge ++ concatLists (map (h: machineAge h.id) (hostsOfDeploymentRole r));
      }) deploymentRoles;

      perCluster = mapAttrsToList (cid: _: {
        path_regex = "^secrets/clusters/${cid}\\.yml$";
        age = fleetAdminAge ++ concatLists (map machineAge (inventory.hostsByCluster.${cid} or [ ]));
      }) clusters;

      cluster = {
        path_regex = "^secrets/cluster\\.yml$";
        age = fleetAdminAge;
      };

      system = {
        path_regex = "^secrets/system\\.yaml$";
        age = fleetAdminAge ++ bootstrapAge ++ concatLists (mapAttrsToList (id: _: machineAge id) hosts);
      };

      yaml = builtins.toJSON {
        creation_rules = [
          cluster
          system
        ]
        ++ perCluster
        ++ perHost
        ++ perDeploymentRole;
      };
    in
    pkgs.runCommand "sops-yaml"
      {
        nativeBuildInputs = [ pkgs.remarshal ];
        yamlInput = yaml;
        passAsFile = [ "yamlInput" ];
      }
      ''
        remarshal -if json -of yaml -i "$yamlInputPath" -o $out
        echo "# AUTO-GENERATED by cluster-config codegen. Do not edit." | cat - $out > $out.tmp
        mv $out.tmp $out
      '';

  matchbox =
    { pkgs }:
    let
      profile = r: {
        id = "deployment-role-${r}";
        name = "Deployment role: ${r}";
        boot = {
          kernel = "/assets/cluster-installer/bzImage";
          initrd = [ "/assets/cluster-installer/initrd" ];
          args = [
            "init=/init"
            "console=ttyS0,115200n8"
            "console=tty0"
            "cluster.deployment-role=${r}"
            "cluster.matchbox=https://matchbox.cluster.local"
          ];
        };
      };

      group = h: {
        inherit (h) id;
        name = h.id;
        profile = "deployment-role-${head h.deployment_roles}";
        selector.mac = primaryMac h;
        metadata = {
          inherit (h) hostname;
          rack = h.location.rack;
          inherit (h) deployment_roles topology_roles;
        };
      };

      profileFiles = mapAttrsToList (r: _: {
        path = "profiles/${r}.json";
        data = builtins.toJSON (profile r);
      }) (filterAttrs (r: _: elem r activeDeploymentRoles) deploymentRoles);

      groupFiles = mapAttrsToList (_: h: {
        path = "groups/${h.id}.json";
        data = builtins.toJSON (group h);
      }) (filterAttrs (_: h: primaryMac h != null) rackedHosts);

      writeAll = concatStringsSep "\n" (
        map (f: ''
                mkdir -p "$(dirname "$out/${f.path}")"
                cat > "$out/${f.path}" <<'EOF'
          ${f.data}
          EOF
        '') (profileFiles ++ groupFiles)
      );
    in
    pkgs.runCommand "matchbox" { } ''
      mkdir -p $out
          ${writeAll}'';

  kea =
    { pkgs }:
    let
      v4nets = filterAttrs (_: n: n.prefix_v4 != null) networks;
      idx = listToAttrs (
        imap1 (i: n: {
          name = n;
          value = i;
        }) (attrNames v4nets)
      );
      subnetId = id: n: if n.vlan_id != null then n.vlan_id + 1 else 1000 + idx.${id};

      subnet4 = mapAttrsToList (id: n: {
        subnet = n.prefix_v4;
        id = subnetId id n;
        reservations = [ ];
        option-data = optionals (n.gateway_v4 != null) [
          {
            name = "routers";
            data = n.gateway_v4;
          }
        ];
        user-context = {
          cluster_network_id = id;
          inherit (n) purpose;
          vrf = n.vrf or "";
        };
      }) v4nets;

      config = {
        Dhcp4 = {
          interfaces-config.interfaces = [ "*" ];
          lease-database = {
            type = "memfile";
            persist = true;
            name = "/var/lib/kea/kea-leases4.csv";
          };
          valid-lifetime = 3600;
          inherit subnet4;
        };
      };
    in
    pkgs.runCommand "kea" { } ''
      mkdir -p $out
          cat > $out/kea-dhcp4.json <<'EOF'
      ${builtins.toJSON config}
      EOF'';

  headscaleAcl =
    { pkgs }:
    let
      activeClusters = filterAttrs (_: c: c.state != "retired") clusters;
      activeTeams = filterAttrs (
        _: t: any (c: any (g: g.team == t.id) c.access.teams) (attrValues activeClusters)
      ) teams;

      stripTag = s: if hasPrefix "tag:" s then substring 4 (stringLength s) s else s;

      baseOf =
        cid:
        let
          c = clusters.${cid};
        in
        if c.network.tailscale_tag != null then stripTag c.network.tailscale_tag else "cluster-${cid}";

      subTagsOf =
        cid:
        let
          base = baseOf cid;
          nonEmpty = bucket: bucket != [ ];
        in
        (optional (nonEmpty (inventory.loginNodesOfCluster.${cid} or [ ])) "tag:${base}-login")
        ++ (optional (nonEmpty (inventory.computeNodesOfCluster.${cid} or [ ])) "tag:${base}-compute")
        ++ (optional (nonEmpty (inventory.storageNodesOfCluster.${cid} or [ ])) "tag:${base}-storage")
        ++ (optional (nonEmpty (
          inventory.controllerNodesOfCluster.${cid} or [ ]
        )) "tag:${base}-controller");

      broadTagOf = cid: "tag:${baseOf cid}";
      fleetAdminTag = "tag:fleet-admin-client";
      metricsTag = "tag:metrics";
      nixCacheTag = "tag:nix-binary-cache";
      fleetServicePorts = {
        logs = 9428;
        nixCache = 5101;
        inbox = 873;
      };
      adminClientHosts = filter (
        h:
        elem "admin-client" (h.topology_roles or [ ])
        && !(elem h.state [
          "retired"
          "decommissioned"
        ])
      ) (attrValues hosts);
      hasAdminClients = adminClientHosts != [ ];
      exporterPortMap = {
        node = 9100;
        smartctl = 9633;
        ipmi = 9290;
        "lm-sensors" = 9100;
        ceph = 9128;
        slurm = 6817;
        zfs = 9134;
      };
      isMonitoredHost =
        h:
        (h.monitoring.enabled or true)
        && !(elem h.state [
          "retired"
          "decommissioned"
        ]);
      monitoredHosts = filter isMonitoredHost (attrValues hosts);
      monitoringPorts = unique (
        concatMap (
          h:
          filter (port: port != null) (
            map (exporter: exporterPortMap.${exporter} or null) (h.monitoring.exporters or [ ])
          )
        ) monitoredHosts
      );

      loginTagOf =
        cid:
        let
          base = baseOf cid;
        in
        if (inventory.loginNodesOfCluster.${cid} or [ ]) != [ ] then "tag:${base}-login" else "tag:${base}";

      computeTagOf =
        cid:
        let
          base = baseOf cid;
        in
        if (inventory.computeNodesOfCluster.${cid} or [ ]) != [ ] then "tag:${base}-compute" else null;
      controllerTagOf =
        cid:
        let
          base = baseOf cid;
        in
        if (inventory.controllerNodesOfCluster.${cid} or [ ]) != [ ] then
          "tag:${base}-controller"
        else
          null;
      storageTagOf =
        cid:
        let
          base = baseOf cid;
        in
        if (inventory.storageNodesOfCluster.${cid} or [ ]) != [ ] then "tag:${base}-storage" else null;

      groups =
        mapAttrs' (tid: t: {
          name = "group:${tid}";
          value = map (m: headscaleId m.user) (filter (m: isActiveUser m.user) t.members);
        }) activeTeams
        // {
          "group:admin" = map headscaleId (attrNames tailnetAdmins);
        };

      tagOwners =
        listToAttrs (
          concatMap (
            cid:
            let
              c = clusters.${cid};
              owners = [ "group:admin" ] ++ map (g: "group:${g.team}") c.access.teams;
              tags = [ (broadTagOf cid) ] ++ subTagsOf cid;
            in
            map (t: {
              name = t;
              value = owners;
            }) tags
          ) (attrNames activeClusters)
        )
        // {
          "tag:bootstrap" = [ "group:admin" ];
          "tag:drive-share" = [ "group:admin" ];
          "tag:drive-access" = [ "group:admin" ];
          ${metricsTag} = [ "group:admin" ];
          ${nixCacheTag} = [ "group:admin" ];
        }
        // optionalAttrs hasAdminClients {
          ${fleetAdminTag} = [ "group:admin" ];
        };

      adminRule = {
        action = "accept";
        src = [ (if hasAdminClients then fleetAdminTag else "group:admin") ];
        dst = (map (cid: "${broadTagOf cid}:*") (attrNames activeClusters)) ++ [ "tag:bootstrap:*" ];
      };

      monitoringRules = concatMap (
        cid:
        let
          controllerTag = controllerTagOf cid;
        in
        optional (controllerTag != null && monitoringPorts != [ ]) {
          action = "accept";
          src = [ controllerTag ];
          dst = map (port: "${metricsTag}:${toString port}") monitoringPorts;
        }
      ) (attrNames activeClusters);

      driveRule = {
        action = "accept";
        src = [ "tag:drive-access" ];
        dst = [ "tag:drive-share:*" ];
      };

      logsRules = concatMap (
        cid:
        let
          controllerTag = controllerTagOf cid;
        in
        optional (controllerTag != null) {
          action = "accept";
          src = [ (broadTagOf cid) ];
          dst = [ "${controllerTag}:${toString fleetServicePorts.logs}" ];
        }
      ) (attrNames activeClusters);

      nixCacheRules = concatMap (
        cid:
        let
          controllerTag = controllerTagOf cid;
        in
        optional (controllerTag != null) {
          action = "accept";
          src = [ nixCacheTag ];
          dst = [ "${controllerTag}:${toString fleetServicePorts.nixCache}" ];
        }
      ) (attrNames activeClusters);

      inboxRules = concatMap (
        cid:
        let
          senders = filter (t: t != null) [
            (controllerTagOf cid)
            (computeTagOf cid)
          ];
        in
        optional (hasAdminClients && senders != [ ]) {
          action = "accept";
          src = senders;
          dst = [ "${fleetAdminTag}:${toString fleetServicePorts.inbox}" ];
        }
      ) (attrNames activeClusters);

      computeMeshRules = concatMap (
        cid:
        let
          ct = computeTagOf cid;
          c = clusters.${cid};
        in
        if ct != null && c.network.intra_cluster == "mesh" then
          [
            {
              action = "accept";
              src = [ ct ];
              dst = [ "${ct}:*" ];
            }
          ]
        else
          [ ]
      ) (attrNames activeClusters);

      loginToComputeRules = concatMap (
        cid:
        let
          base = baseOf cid;
          haveLogin = (inventory.loginNodesOfCluster.${cid} or [ ]) != [ ];
          ct = computeTagOf cid;
        in
        if haveLogin && ct != null then
          [
            {
              action = "accept";
              src = [ "tag:${base}-login" ];
              dst = [ "${ct}:22" ];
            }
          ]
        else
          [ ]
      ) (attrNames activeClusters);

      computeToStorageRules =
        let
          intra = concatMap (
            cid:
            let
              c = clusters.${cid};
              ct = computeTagOf cid;
              st = storageTagOf cid;
              ports = c.network.storage.ports_tcp;
            in
            if ct != null && st != null && ports != [ ] then
              map (p: {
                action = "accept";
                src = [ ct ];
                dst = [ "${st}:${toString p}" ];
              }) ports
            else
              [ ]
          ) (attrNames activeClusters);
          inter = concatMap (
            cid:
            let
              c = clusters.${cid};
              ct = computeTagOf cid;
            in
            if ct == null then
              [ ]
            else
              concatMap (
                otherCid:
                if !(clusters ? ${otherCid}) then
                  [ ]
                else
                  let
                    other = clusters.${otherCid};
                    st = storageTagOf otherCid;
                    ports = other.network.storage.ports_tcp;
                  in
                  if st != null && ports != [ ] then
                    map (p: {
                      action = "accept";
                      src = [ ct ];
                      dst = [ "${st}:${toString p}" ];
                    }) ports
                  else
                    [ ]
              ) c.network.egress.clusters
          ) (attrNames activeClusters);
        in
        intra ++ inter;

      teamGrantRules = concatMap (
        cid:
        let
          c = clusters.${cid};
        in
        map (g: {
          action = "accept";
          src = [ "group:${g.team}" ];
          dst = [ "${loginTagOf cid}:*" ];
        }) c.access.teams
      ) (attrNames activeClusters);

      userGrantRules = concatMap (
        cid:
        let
          c = clusters.${cid};
        in
        map (g: {
          action = "accept";
          src = [ (headscaleId g.user) ];
          dst = [ "${loginTagOf cid}:*" ];
        }) (filter (g: isActiveUser g.user) c.access.users)
      ) (attrNames activeClusters);

      egressClusterRules = concatMap (
        cid:
        let
          c = clusters.${cid};
        in
        concatMap (
          otherCid:
          if !(clusters ? ${otherCid}) then
            [ ]
          else
            map (g: {
              action = "accept";
              src = [ "group:${g.team}" ];
              dst = [ "${loginTagOf otherCid}:*" ];
            }) c.access.teams
        ) c.network.egress.clusters
      ) (attrNames activeClusters);

      teamSubmitRules = concatMap (
        cid:
        let
          c = clusters.${cid};
        in
        concatMap (
          g:
          map (otherCid: {
            action = "accept";
            src = [ "group:${g.team}" ];
            dst = [ "${loginTagOf otherCid}:*" ];
          }) g.can_submit_to
        ) c.access.teams
      ) (attrNames activeClusters);

      userSubmitRules = concatMap (
        cid:
        let
          c = clusters.${cid};
        in
        concatMap (
          g:
          map (otherCid: {
            action = "accept";
            src = [ (headscaleId g.user) ];
            dst = [ "${loginTagOf otherCid}:*" ];
          }) g.can_submit_to
        ) (filter (g: isActiveUser g.user) c.access.users)
      ) (attrNames activeClusters);

      acls = [
        adminRule
        driveRule
      ]
      ++ monitoringRules
      ++ logsRules
      ++ nixCacheRules
      ++ inboxRules
      ++ computeMeshRules
      ++ loginToComputeRules
      ++ computeToStorageRules
      ++ teamGrantRules
      ++ userGrantRules
      ++ egressClusterRules
      ++ teamSubmitRules
      ++ userSubmitRules;

      nodeAttrs = [
        {
          target = [ "tag:drive-share" ];
          attr = [ "drive:share" ];
        }
        {
          target = [ "tag:drive-access" ];
          attr = [ "drive:access" ];
        }
      ];

      grants = [
        {
          src = [ "tag:drive-access" ];
          dst = [ "tag:drive-share" ];
          app = {
            "tailscale.com/cap/drive" = [
              {
                shares = [ "*" ];
                access = "rw";
              }
            ];
          };
        }
      ];

      policy = headscalePolicy.mk {
        inherit
          groups
          tagOwners
          acls
          nodeAttrs
          grants
          ;
      };

      policyFile = headscalePolicy.write {
        inherit pkgs policy;
        name = "policy.hujson";
        comments = [
          "AUTO-GENERATED by cluster-config codegen. Do not edit."
          ""
          "Derived from cluster access, teams, users with tailnet admin scope, and host"
          "topology roles. Deployment roles and Unix tiers do not grant Tailnet authority."
          "Regenerate with `nix build .#headscale-acl`."
          ""
          "Tag ownership and ACL names do not assign tags to nodes. Promote verified"
          "nodes manually; only the quarantine tag:bootstrap is assigned during enrolment."
          ""
          "Layers of enforcement (this is the outermost):"
          "  1. headscale ACL (this file)        - reachability on the overlay"
          "  2. nftables on each host (TODO)     - L3/L4 packet filter"
          "  3. slurm AssocMgr / partition QoS   - job submission"
          "  4. pam_slurm_adopt + sshd Match     - SSH only if user has alloc"
        ];
      };
    in
    pkgs.runCommand "headscale-acl" { } ''
      mkdir -p "$out"
      cp ${policyFile} "$out/policy.hujson"
    '';

  hostNetFacts = mapAttrs (_: h: {
    hostId = h.id;
    inherit (h) hostname;
    inherit (h) location;
    nics = map (n: n // { network = networks.${n.network} or { }; }) h.nics;
    inherit (h) bgp;
    cluster = inventory.hostToCluster.${h.id} or null;
    ownerTeam = inventory.hostOwnerTeam.${h.id} or null;
  }) hosts;
}
